### ISSUE TITLE
unicode support, add min chars left and transferred

### ISSUE THREAD

**Issue by vasilich-tregub** [mysolution/hyphenator#2]
I edited your excellent project and added Unicode support. Mostly it is changing type char to wchar_t, like this:

from file patterns.h:

const wchar_t* patterns[] = {
L".аб1р",
L".аг1ро",
L".ади2",
...

from file hyphenator.h:

struct word_hyphenation_t {
	wchar_t* mask;
	unsigned long mask_size;
};

//callbacks
typedef int (*isdigit_callback_t)(wchar_t c);
typedef int (*ismarker_callback_t)(wchar_t c);
typedef wchar_t (*char2digit_callback_t)(wchar_t c);

...

etc.

If someone be interested, I will publish my code.

Besides, I added parameters min chars left in a line and min chars, transferred to the next line, like this:

(from file hyphenator.cpp, hyphenate_word procedure):

	wh->mask_size = levels.size()-2;
	wh->mask = new wchar_t[wh->mask_size];
	// chars left on a current line
	int charsLeft = 5;
	// chars transferred to the next line
	int charsTransferred = 3;
	for (size_t i = 0; i < wh->mask_size; ++i)
	{
		if (levels[i+1] % 2 && i) 
			wh->mask[i] = 1;
		else 
			wh->mask[i] = 0;
			if (i < charsLeft) wh->mask[i] = 0; 
			if (i > (wh->mask_size - charsTransferred) && charsTransferred < wh->mask_size) wh->mask[i] = 0;
	}
		
	return wh;
}

**Comment by mysolution** [comment]
You can simply edit typedef 'unichar' https://github.com/mysolution/hyphenator/blob/master/hyphenator.h#L12

word_hyphenation_t::mask should not be wchar_t, it's array with 0/1 values.

**Comment by vasilich-tregub** [comment]
Agreed.
